### ISSUE TITLE
optionOrAlt key for Mac and Windows unification.

### ISSUE THREAD

**Issue by ryanpeach** [serenadeai/serenade#20]
## Context

There is a modifier `commandOrControl` for key presses that switches depending on whether or not you are on mac between command (Mac) or control (Windows). Similarly there should be an `optionOrAlt` key. This is even more intuitive since mac doesn't have an alt, but it does have a seperate control and command key.

I should be able to do this, just noting it down here.

**Comment by tmacwill** [comment]
thanks for the suggestion! I believe this should be happening already based on:
* https://github.com/serenadeai/driver/blob/master/src/windows.cpp#L283
* https://github.com/serenadeai/driver/blob/master/src/mac.cpp#L699

but, if that's not working please reopen this! `commandOrControl` exists because Macs have both a command and control key, whereas the option key replaces the alt key.
